### ISSUE TITLE
chectl server:start timeout -> downloading images

### ISSUE THREAD

**Issue by ye1984** [che-incubator/che-demos#9]
Hello,

I'm trying to run the demo, but after running this command : `chectl server:start --k8spodwaittimeout=600000` . An error is occured on the downloading images step.

Do you have an idea ? 

Stack : MacOs Sierra 10.12 

> ✈️  Minikube preflight checklist
>     ✔ Verify if kubectl is installed
>     ✔ Verify if minikube is installed
>     ✔ Verify if minikube is running
>     ↓ Start minikube [skipped]
>       → Minikube is already running.
>     ✔ Verify if minikube ingress addon is enabled
>     ↓ Enable minikube ingress addon [skipped]
>       → Ingress addon is already enabled.
>     ✔ Retrieving minikube IP and domain for ingress URLs...192.168.99.101.nip.io.
>   ✔ 🏃‍  Running Helm to install Che
>     ✔ Verify if helm is installed
>     ✔ Create Tiller Role Binding...it already exist.
>     ✔ Create Tiller Service Account...it already exist.
>     ✔ Create Tiller RBAC
>     ✔ Create Tiller Service...it already exist.
>     ✔ Preparing Che Helm Chart...done.
>     ✔ Updating Helm Chart dependencies...done.
>     ✔ Deploying Che Helm Chart...done.
>   ❯ ✅  Post installation checklist
>     ❯ Che pod bootstrap
>       ✔ scheduling...done.
>       ✖ downloading images
>         → ERR_TIMEOUT: Timeout set to pod wait timeout 600000
>         starting
>       Retrieving Che Server URL
>       Che status check
> Error: ERR_TIMEOUT: Timeout set to pod wait timeout 600000
>     at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
>     at Generator.next (<anonymous>)
>     at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:104:62)

**Comment by benoitf** [comment]
hello, could you increase that timeout ?
also do you have slow network (to pull docker image ?)

**Comment by ye1984** [comment]
I already increased the timeout.

Slow network probably :). At home, my network is slow, but before running this command, I downloaded all necessary tools (from scratch) using my slow network.

But I think, you are right, I will test tomorrow at work. The network is more faster :)

I will let you know tomorrow

**Comment by benoitf** [comment]
you can monitor events like using `kubectl get events --namespace che`

**Comment by ye1984** [comment]
After many try, the download step works fine :)  but now I have this same issue : 
https://github.com/che-incubator/chectl/issues/124#issue-451228701
